global using Carter;
global using FluentValidation;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.Identity.Web;
global using RepoCentral.Core.Behaviors;
global using RepoCentral.Core.Exceptions.Handler;
global using RepoCentral.Application.DTOs;
global using System.Reflection;
global using MediatR;
